API/feature: adicionando endpoint da lista de produtos
DGFS02/digital-store-backend pull request #2
Opened 2023-01-14 18:29 UTC by chicaofmp

Usando MOCK dentro do res.JSON, necessário utilizar a futura api de lista de produtos

2023-01-14 18:47 UTC, mdsjjorge requested changes

2023-01-14 18:47 UTC, mdsjjorge commented on app.js
> +var productListRouter = require('./routes/api')
alterar nome productListRouter para apiRouter

2023-01-14 18:47 UTC, mdsjjorge commented on app.js
> +app.use(productListRouter)
alterar para app.use('/api', apiRouter);

2023-01-14 19:06 UTC, mdsjjorge approved these changes

2023-01-28 16:53 UTC, daniloteofilo approved these changes
Tudo revisado e adequado

2023-01-28 16:54 UTC, merged