add-localhost-to-readme
DGFS02/digital-store-backend pull request #5
Opened 2023-01-28 17:36 UTC by mrcsporto

update readme documentation

2023-02-04 17:06 UTC, carlosxjm requested changes

2023-02-04 17:06 UTC, carlosxjm commented on README.md
> +$ http://localhost:3000/
I didn't get the reason of this change

2023-02-04 19:28 UTC, Gabriel-Vasconcelos reviewed
Não entendi

2023-02-11 16:28 UTC, mrcsporto commented
PR closed

2023-02-11 16:28 UTC, closed without merging