Adicionando arquivo .env
DGFS02/digital-store-backend pull request #8
Opened 2023-02-04 16:32 UTC by BrunoAAM

2023-02-04 16:56 UTC, carlosxjm requested changes
Would be great to add some instructions to the README file .
Just a suggestion how the user should create the env file copy:
```
cp .env.example .env
```

2023-02-04 16:56 UTC, carlosxjm commented on .env.example
> +DB_Dialect=mysql
Add blank line at the end of the file.

2023-02-04 16:56 UTC, carlosxjm commented on .env.example
> +DB_Dialect=mysql
Please, check all files with the same issue.

2023-02-11 18:08 UTC, Gabriel-Vasconcelos approved these changes
brabo

2023-02-11 18:08 UTC, carlosxjm approved these changes

2023-02-11 18:10 UTC, merged